"""Stream-copy MPEG-TS segments through PyAV to fix ExoPlayer audio.

Vavoo (and similar IPTV CDNs) often serve TS segments at 44.1 kHz AAC,
which ExoPlayer on Fire TV / Android TV silently fails to decode (no
sound, no error). The fix is to resample audio to 48 kHz — the standard
broadcast sample rate that ExoPlayer hardware decoders all handle.

Pipeline (when EXOPLAYER_REMUX=true):
- Video: stream-copy (no re-encode, preserves quality)
- Audio: decode AAC -> resample to 48 kHz stereo -> encode AAC LC 128k

PMT/PCR are regenerated by `mux()` automatically. CPU cost is dominated
by the audio re-encode (~5-8% per concurrent stream on 0.1 vCPU); video
copy is essentially free.

On any failure the original bytes are returned unchanged, so this is
safe to enable globally — no segment is ever lost.
"""

import asyncio
import io
import logging

import av
from av.audio.resampler import AudioResampler

logger = logging.getLogger(__name__)


def _remux_ts_sync(input_bytes: bytes) -> bytes:
    in_buf = io.BytesIO(input_bytes)
    out_buf = io.BytesIO()

    in_container = av.open(in_buf, mode="r", format="mpegts")
    try:
        out_container = av.open(out_buf, mode="w", format="mpegts")
        try:
            video_in = audio_in = None
            for s in in_container.streams:
                if s.type == "video" and video_in is None:
                    video_in = s
                elif s.type == "audio" and audio_in is None:
                    audio_in = s

            if video_in is None and audio_in is None:
                return input_bytes

            video_out = out_container.add_stream_from_template(video_in) if video_in else None

            audio_out = None
            resampler = None
            if audio_in is not None:
                audio_out = out_container.add_stream("aac", rate=48000)
                audio_out.bit_rate = 128_000
                audio_out.layout = "stereo"
                resampler = AudioResampler(format="fltp", layout="stereo", rate=48000)

            for packet in in_container.demux():
                if packet.dts is None:
                    continue
                if video_in is not None and packet.stream.index == video_in.index:
                    packet.stream = video_out
                    out_container.mux(packet)
                elif audio_in is not None and packet.stream.index == audio_in.index:
                    for frame in packet.decode():
                        for resampled in resampler.resample(frame):
                            for enc_pkt in audio_out.encode(resampled):
                                out_container.mux(enc_pkt)

            if audio_out is not None:
                for enc_pkt in audio_out.encode(None):
                    out_container.mux(enc_pkt)
        finally:
            out_container.close()
    finally:
        in_container.close()

    remuxed = out_buf.getvalue()
    return remuxed if remuxed else input_bytes


async def remux_ts_for_exoplayer(input_bytes: bytes) -> bytes:
    """Async wrapper. Falls back to the original bytes on any error."""
    if not input_bytes:
        return input_bytes
    try:
        return await asyncio.to_thread(_remux_ts_sync, input_bytes)
    except Exception as e:
        logger.warning("Exoplayer TS remux failed (%s bytes): %s — passthrough", len(input_bytes), e)
        return input_bytes
